<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Privacy Policy_lni-close</name>
   <tag></tag>
   <elementGuidId>a2bafb84-7d8d-4d23-abf0-d135faf224a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='donate']/div/div/div/div/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.lni-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lni-close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;donate&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content light-brown-bg&quot;]/div[@class=&quot;modal-header pb-0 pt-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 text-center-xs&quot;]/a[@class=&quot;close pull-right text-brown mt-25&quot;]/i[@class=&quot;lni-close&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='donate']/div/div/div/div/div/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
   </webElementXpaths>
</WebElementEntity>
