<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Demo 1.1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4e92eb1c-118a-406d-9364-0b6b38a54d0b</testSuiteGuid>
   <testCaseLink>
      <guid>e095fd89-5dfb-401c-9563-332dab757e3f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Older Test Cases/Navigation 1</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c1e84087-21d8-46fe-a783-73a665e579cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Older Test Cases/IEO Login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>57e708ff-d469-45f9-809f-1a94e6f871a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Older Test Cases/Edit Profile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b650114e-cc5e-46b9-9f0a-9387489b7b26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d882c950-513e-44aa-b188-8d7252054fdc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>465f284e-6f96-4e11-99f2-9cef048c2c7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22e1de41-9ef7-4d6c-b8e9-3b583cc41395</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55eab6f9-4cb9-463e-a7d5-ed988741bbc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>623fb3e3-fc3a-4c16-ae53-13da592c55cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e531cee-c6df-475f-99e4-f4947ba18fed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>443ba564-35f2-464e-94cc-60fbd99040ff</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
