<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Asha  Vin_fa fa-angle-down</name>
   <tag></tag>
   <elementGuidId>834fd33a-e8b1-4cf7-8d29-7cc071c49edd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='primary-nav']/li[5]/a/span/span[2]/span[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-angle-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-down</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primary-nav&quot;)/li[@class=&quot;menu-item-has-children position-applied active&quot;]/a[1]/span[@class=&quot;hidden-xs hidden-sm hidden-md&quot;]/span[@class=&quot;link-txt&quot;]/span[@class=&quot;txt pl-1&quot;]/i[@class=&quot;fa fa-angle-down&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='primary-nav']/li[5]/a/span/span[2]/span[2]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
   </webElementXpaths>
</WebElementEntity>
